# Generated by Django 4.2 on 2024-04-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.IntegerField(verbose_name=15),
        ),
    ]
