# Generated by Django 4.2 on 2024-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_register_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
