# Generated by Django 4.2 on 2024-04-12 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_register_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickupLocation", models.CharField(max_length=100)),
                ("dropoffLocation", models.CharField(max_length=100)),
                (
                    "pickupDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "dropoffDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("cartype", models.CharField(max_length=100)),
            ],
        ),
    ]
